module.exports = {
  Egg: require("./egg"),
  Generation: require("./generation"),
  GlobalStat: require("./global-stat"),
  MaxBattle: require("./max-battle"),
  Move: require("./move"),
  Pokemon: require("./pokemon"),
  PokemonAsset: require("./pokemon-asset"),
  Raid: require("./raid"),
  Research: require("./research"),
  Region: require("./region"),
  Rocket: require("./rocket"),
  SyncRun: require("./sync-run"),
  Type: require("./type"),
  Weather: require("./weather"),
};
