module.exports = {
  BestAttacker: require("./best-attacker"),
  Egg: require("./egg"),
  Generation: require("./generation"),
  GlobalStat: require("./global-stat"),
  Item: require("./item"),
  MaxBattle: require("./max-battle"),
  Move: require("./move"),
  Pokemon: require("./pokemon"),
  PokemonAsset: require("./pokemon-asset"),
  PokemonIdentityMapping: require("./pokemon-identity-mapping"),
  PvpRanking: require("./pvp-ranking"),
  Raid: require("./raid"),
  Research: require("./research"),
  Region: require("./region"),
  Rocket: require("./rocket"),
  RocketText: require("./rocket-text"),
  ShinyRanking: require("./shiny-ranking"),
  ShinySnapshot: require("./shiny-snapshot"),
  SyncRun: require("./sync-run"),
  Type: require("./type"),
  Weather: require("./weather"),
};
